[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200          ; serial monitor baud rate
build_flags = -DCORE_DEBUG_LEVEL=4   ; debug log level
lib_deps = pschatzmann/ESP32-A2DP   ; Bluetooth A2DP audio library
